apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mount-file
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: index-vol
          mountPath: /usr/share/nginx/html
          subPath: index.html
        - name: cache-vol
          mountPath: /nginx_cache
      volumes:
        - name: index-vol
          configMap:
            name: index-configmap
            items:
              - key: nginx_index.html
                path: index.html
        - name: cache-vol
          emptyDir: {}