---
kind: Pod
apiVersion: v1
metadata:
  name: csi-pod
spec:
  containers:
    - image: busybox
      name: app
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /data/test.txt; sleep 10; done
      volumeMounts:
        - mountPath: /data
          name: mydata
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: csi-pvc
