apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-storage-webapp-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-hostpath-sc-retain
  dataSource:
    name: webapp-0-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io