apiVersion: v1
kind: Namespace
metadata:
  name: velero-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: velero-demo
data:
  config_data: MyImportantConfigData
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-app
  namespace: velero-demo
spec:
  serviceName: "demo-app"
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: busy
          image: busybox
          command: ["sh", "-c"]
          args:
            - echo "Persistent data on $(hostname) - $(date)" >> /data/file.txt && sleep 3600
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config-volume
              mountPath: /etc/custom_config
              subPath: config_data
      volumes:
        - name: config-volume
          configMap:
            name: demo-config
            items:
              - key: config_data
                path: config_data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: csi-hostpath-sc
      resources:
        requests:
          storage: 100Mi